### ISSUE TITLE
Sleep Issues

### ISSUE THREAD

**Issue by mrbubzie93** [b00t0x/GPD-WIN-Max-Hackintosh#3]
GPD win max will go to sleep but if you wake it up and try to go back to sleep mac os kernel panics and restarts.  Happening on big sur, and Monterey.

**Comment by b00t0x** [comment]
@mrbubzie93 This guide may fix the issue.

https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#preparations
```
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0
```

**Comment by b00t0x** [comment]
And I made some fix to solve the issue.
4321bcb
