### ISSUE TITLE
Ventura bluetooth fix, controller as mouse and sd card improvements

### ISSUE THREAD

**Issue by postkevone** [b00t0x/GPD-WIN-Max-Hackintosh#8]
I was able to fix the bluetooth on Ventura by following [this guide](https://elitemacx86.com/threads/intel-bluetooth-not-working-on-ventura.1274) and using these kexts [IntelBluetooth_winmax.zip](https://github.com/b00t0x/GPD-WIN-Max-Hackintosh/files/11994266/IntelBluetooth_winmax.zip).

```
Add the following keys in the NVRAM>add>7C436110-AB2A-4BBB-A880-FE41995C9F82 section of your config.plist
bluetoothInternalControllerInfo: 00000000 00000000 00000000 0000
bluetoothExternalDongleFailed: 00
Set the Type to DATA.
Restart the system and reset NVRAM twice.
```

I was also able to get 360Controller driver working by using the [latest alpha version](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.6) and by disabling sip.
Better mouse movement with the controller than Voodoo can be achieved by using [Enjoyable](https://github.com/shirosaki/enjoyable), which works flawlessly.

I also want to reccomend an app called [Jettison](https://www.stclairsoft.com/Jettison/) which ejects the SD card before sleep or shutdown. With this you can keep your SD card always inside without worrying about damaging it

**Comment by b00t0x** [comment]
Thank you for the information.

By https://github.com/acidanthera/BrcmPatchRAM/pull/31, it looks like the next release of BlueToolFixup will not require NVRAM fix.

To support Sonoma, I'm planning to update the repository when OpenCore 0.9.4 and BlueToolFixup 2.6.8 comes out.

**Comment by b00t0x** [comment]
Updated kexts with #9. I also included the 360Controller.kext in the EFI so there is no need to disable SIP.
